/* --------------------------------------------------------------------------
 * SerialWeb locale data.
 *
 * Standalone script on purpose: it is not part of the shared app closure, so it
 * can be loaded before the app chunks and stays readable on its own. Keys are
 * the Chinese source strings, which means a missing entry degrades to Chinese
 * instead of leaking a raw key into the UI.
 *
 * `{{name}}` in a value is filled by t(key, { name }) at the call site, so a
 * key that contains a placeholder must keep the placeholder name identical.
 * Whitespace inside a key is the collapsed form of markup that wraps in the
 * source; the lookup falls back to that collapsed form automatically.
 * ------------------------------------------------------------------------*/
(function () {
  'use strict';

  var en = {
    /* Brand, chrome, menus */
    '系统菜单': 'System Menu',
    '主题': 'Theme',
    '主题：': 'Theme:',
    '浅色模式': 'Light',
    '深色模式': 'Dark',
    '跟随系统': 'System',
    '语言：': 'Language:',
    '中文': '中文',
    '跟随应用': 'Follow app',
    '模式': 'Mode',
    '模式切换': 'Switch mode',
    '监视': 'Monitor',
    '解析': 'Parse',
    '终端': 'Terminal',
    '图形解析': 'Graphs',
    '图形解析模式': 'Graph mode',
    '离线': 'Offline',
    '工具手册': 'Manual',
    '查看工具手册': 'View the manual',
    '问题反馈': 'Feedback',
    '提交问题反馈': 'Send feedback',
    '查看 github 项目': 'View the GitHub project',
    '源码仓库': 'Source code',
    '许可证': 'License',
    '查看 AGPL-3.0 许可证': 'Read the AGPL-3.0 license',
    '串口监视与图形解析工具': 'Serial monitor and graph parsing tool',
    '分叉来源': 'Fork provenance',
    'SerialWeb 由电导实验室（Conductance-lab）创作，本仓库是它的独立分叉；分叉点之前的代码归原作者，两者一律按 AGPL-3.0 授权。': 'SerialWeb was created by Conductance-lab. This repository is an independent fork of it: the code before the divergence point belongs to the original author, and both are offered under AGPL-3.0.',
    '分叉自上游 v1.6（提交 e3f9200814，2026/9/6），即本仓库的 v0.1.0。': 'Forked from upstream v1.6 (commit e3f9200814, 2026/9/6), which is v0.1.0 of this repository.',
    '原作者主页': 'Author home page',
    '上游仓库': 'Upstream repo',
    '上游在线版本': 'Upstream online',
    '上游工具手册': 'Upstream manual',
    '原始反馈表单': 'Original feedback form',
    '关于 v{{version}}': 'About v{{version}}',
    '更新日志': 'Changelog',
    '关闭版本信息': 'Close version info',
    '关闭提示': 'Dismiss',
    '当前版本': 'Current version',
    '最新在线版本': 'Latest online version',
    '当前在线最新': 'Already the latest',
    '在线版本 v{{version}}': 'Online v{{version}}',
    'SerialWeb 在线版本 v{{version}}': 'SerialWeb Online v{{version}}',
    '离线版本 v{{version}}': 'Offline v{{version}}',
    'SerialWeb 离线版本 v{{version}}': 'SerialWeb Offline v{{version}}',
    '访问在线模式': 'Switch to online mode',
    '打开在线版本': 'Open the online version',
    '当前已是在线版本': 'You are on the online version',
    '下载离线版到本地': 'Download the offline build',
    '开始准备下载': 'Preparing download',
    '请在浏览器弹出的另存为窗口中保存离线版。': 'Save the offline page in the browser dialog.',
    '下载已触发': 'Download started',
    '请在另存为窗口中确认保存。': 'Confirm the location in the save dialog.',
    '下载失败': 'Download failed',
    '离线页面无法重新获取 index.html。': 'The offline page cannot fetch index.html.',
    '当前站点没有返回完整的页面资源，请稍后重试。': 'This site did not return the full page assets, please try again later.',

    /* Connection management */
    '设备连接管理': 'Device connection manager',
    '展开/折叠连接管理': 'Expand/collapse connection manager',
    '串口监视器': 'Serial monitor',
    '波特率': 'Baud rate',
    '选择常用波特率': 'Pick a common baud rate',
    '数据位': 'Data bits',
    '停止位': 'Stop bits',
    '校验位': 'Parity',
    '偶校验': 'Even',
    '奇校验': 'Odd',
    '无': 'None',
    'RTS/CTS 流控': 'RTS/CTS flow control',
    '自动控制与硬件流控': 'Auto control and hardware flow control',
    '手动控制 RTS': 'Manual RTS control',
    'RTS/CTS 流控生效时，RTS 由系统自动接管。': 'With RTS/CTS flow control enabled, the system takes over RTS.',
    '失焦自动断连': 'Release on blur',
    '自动重连': 'Auto reconnect',
    '字符编码': 'Text encoding',
    '显示时间': 'Show timestamps',
    '十六进制接收': 'Hex receive',
    '十六进制发送': 'Hex send',
    '换行符设置': 'Line ending',
    '换行': 'Line feed',
    '发送时追加的行结束符': 'Line ending appended when sending',
    '结尾补换行符': 'Append line ending',
    '到底部': 'Scroll to bottom',
    '滚动到底部': 'Scroll to the bottom',
    '调整串口监视器与发送功能区域高度': 'Resize the monitor and send panels',

    /* Connect button and serial state */
    '连接设备 | 当前未连接': 'Connect | not connected',
    '连接串口设备': 'Connect a serial device',
    '断开串口连接': 'Disconnect',
    '断开连接 | {{elapsed}}': 'Disconnect | {{elapsed}}',
    '失焦断连 | {{elapsed}}': 'Released on blur | {{elapsed}}',
    '正在应用参数 | 请稍候': 'Applying settings | please wait',
    '正在重连 | 点击取消重连': 'Reconnecting | click to cancel',
    '重连失败 | 串口可能被占用': 'Reconnect failed | port may be in use',
    '{{action}} | 串口可能被占用': '{{action}} | port may be in use',
    '串口已连接': 'Serial port connected',
    '串口已连接，波特率 {{baudRate}}。': 'Serial port connected at {{baudRate}} baud.',
    '串口已断开。': 'Serial port closed.',
    '串口连接已丢失。': 'Serial connection lost.',
    '页面失焦，已释放串口连接。': 'Page lost focus, the serial port was released.',
    '串口未连接': 'Serial port not connected',
    '串口未连接，无法发送当前内容。': 'Serial port not connected, cannot send the current content.',
    '串口未连接，无法发送终端输入。': 'Serial port not connected, cannot send terminal input.',
    '串口操作失败': 'Serial operation failed',
    '串口连接失败': 'Serial connection failed',
    '串口写入失败。': 'Serial write failed.',
    '当前串口句柄不可用，请重新连接设备。': 'The serial handle is no longer valid, reconnect the device.',
    '串口已被占用，请关闭其他串口软件后重试': 'The port is in use, close other serial tools and retry',
    '串口已被占用或当前状态不可操作': 'The port is in use or not in a usable state',
    '串口可能被占用，请关闭其他串口软件后重试': 'The port may be in use, close other serial tools and retry',
    '串口访问被拒绝，请检查系统权限': 'Serial access denied, check the system permissions',
    '串口设备已断开或不可用': 'The serial device was disconnected or is unavailable',
    '未选择串口设备': 'No serial device selected',
    '用户取消了串口选择。': 'You cancelled the device picker.',
    '等待串口数据': 'Waiting for serial data',
    '等待串口恢复可用': 'Waiting for the serial port to become available',
    '等待原串口设备恢复': 'Waiting for the original device to return',
    '连接暂停中': 'Connection paused',
    '连接失败': 'Connection failed',
    '连接失败: {{detail}}': 'Connection failed: {{detail}}',
    '重连失败': 'Reconnect failed',
    '重连失败: {{detail}}': 'Reconnect failed: {{detail}}',
    '自动重连失败': 'Auto reconnect failed',
    '参数未应用': 'Settings not applied',
    '发送失败': 'Send failed',
    '发送失败：{{message}}': 'Send failed: {{message}}',
    '接收数据处理失败: {{error}}': 'Receive processing failed: {{error}}',
    '不支持 Web Serial API': 'Web Serial API not supported',
    '推荐使用 Chrome 或 Edge，并访问在线最新版本：{{url}}': 'Use Chrome or Edge and open the latest online version: {{url}}',
    '不支持 Web Serial API。推荐使用 Chrome 或 Edge，并访问在线最新版本：{{url}}': 'Web Serial API is not supported. Use Chrome or Edge and open the latest online version: {{url}}',
    'Web Serial API 已就绪，等待连接。': 'Web Serial API ready, waiting for a connection.',
    '浏览器未提供': 'Not provided by the browser',
    '就绪，等待连接': 'Ready, waiting to connect',
    '开': 'On',
    '关': 'Off',

    /* Monitor view */
    '串口监视': 'Serial monitor',
    '串口离线': 'Serial offline',
    '监视视图切换': 'Switch monitor view',
    '手动收发': 'Manual',
    '当前没有日志内容': 'No log content yet',
    '终端交互模式': 'Terminal mode',
    '串口终端，直接键入内容，回车发送': 'Serial terminal, type to send, Enter to transmit',
    '本地回显键入内容（仅适用于不回显的设备；shell 等设备会自行回显，保持关闭）': 'Echo typed characters locally (only for devices that do not echo; a shell echoes itself, so keep this off)',
    '回显': 'Echo',
    '终端字体（可选 Nerd Font 等已安装字体）': 'Terminal font (any installed font, Nerd Font included)',
    '终端字号（8-48，可在终端内 Ctrl + 滚轮缩放）': 'Terminal font size (8-48, Ctrl+wheel inside the terminal also zooms)',
    '终端配色主题': 'Terminal colour theme',
    '未检测到该字体，已回退为默认等宽字体': 'Font not detected, falling back to the default monospace',
    '—— 串口终端已就绪：直接键入即发送（Ctrl+C/Ctrl+D/方向键等原样透传给设备）；如设备不回显，请打开“回显” ——': '—— Serial terminal ready: type to send (Ctrl+C/Ctrl+D/arrows pass through as-is); turn on Echo if the device does not echo ——',
    '字体': 'Font',
    '字号': 'Size',
    '默认': 'Default',
    '黑底白字': 'Black on white',
    '黑底绿字': 'Black on green',
    '更纱黑体': 'Sarasa Gothic',

    /* Timeline */
    '展开时间线列表': 'Expand the timeline list',
    '实时模式': 'Realtime',
    '回放模式': 'Playback',
    '当前录制中': 'Recording now',
    '串口实时数据流': 'Live serial stream',
    '实时解析结果': 'Live parse results',
    '冻结实时视图': 'Freeze the live view',
    '解除冻结实时视图': 'Unfreeze the live view',
    '开始录制': 'Start recording',
    '结束录制': 'Stop recording',
    '录制 {{elapsed}} · {{latest}}': 'Recording {{elapsed}} · {{latest}}',
    '最新 {{stamp}}': 'Latest {{stamp}}',
    '{{count}} 段 · {{duration}}': '{{count}} chunks · {{duration}}',
    '导入时间线': 'Import timeline',
    '从 BIN / TXT / CSV 时间线文件导入原始数据与配置': 'Import raw data and settings from a BIN / TXT / CSV timeline',
    '导出时间线': 'Export timeline',
    '导出解析结果': 'Export parse results',
    '可录制时间线导出解析结果': 'Export parse results from a recorded timeline',
    '粘贴导入': 'Paste',
    '复制配置': 'Copy',
    '配置文本': 'Settings text',
    '配置：': 'Settings:',
    '播放回放': 'Play back',
    '暂停回放': 'Pause playback',
    '时间线支持导入/导出 BIN/TXT/CSV 原始文件及 TXT/CSV 解析结果。': 'Timelines import and export BIN/TXT/CSV raw data plus TXT/CSV parse results.',

    /* Parser */
    '解析协议设置': 'Protocol settings',
    '文本解析': 'Text parsing',
    '文本解析配置': 'Text parse settings',
    '十六进制解析': 'Hex parsing',
    '十六进制结构表': 'Hex structure table',
    '数值 / 数据类型': 'Value / data type',
    '段类型': 'Row type',
    '标签': 'Label',
    '帧头': 'Header',
    '帧尾': 'Footer',
    '数据': 'Data',
    '校验和': 'Checksum',
    '间隔符': 'Gap',
    '16进制帧头': 'Hex header',
    '16进制数值': 'Hex value',
    '留空则不匹配帧尾': 'Leave empty to skip the footer',
    '留空则仅占位，否则进行匹配': 'Leave empty for a one-byte placeholder, or match this value',
    'name 标签': 'name label',
    '新增一行': 'Add row',
    '删除此行': 'Delete this row',
    '删除': 'Delete',
    '自动识别': 'Auto detect',
    '自动识别：不可用': 'Auto detect: unavailable',
    '自动识别：可用': 'Auto detect: available',
    '发现解析可用': 'Pattern found',
    '检测到稳定的文本解析模板，可直接应用，并自动添加时域图与频域图。': 'A stable text pattern was detected. Apply it to add a time and a frequency chart.',
    '应用添加并转到': 'Apply, add and go',
    '展开': 'Expand',
    '折叠': 'Collapse',
    '展开实时解析结果': 'Expand the live parse results',
    '折叠实时解析结果': 'Collapse the live parse results',
    '暂无解析结果': 'No parse results yet',
    '数据绑定': 'Data binding',
    '通道': 'Channels',
    '全部通道': 'All channels',
    '全部': 'All',
    '暂无数值通道': 'No numeric channels yet',
    '时域图': 'Time chart',
    '频域图': 'Frequency chart',
    '柱状图': 'Bar chart',
    '添加图框': 'Add chart',
    '当前还没有图表，点击上方添加时域或频域图。': 'No charts yet. Add a time or frequency chart above.',
    '时域图 {{index}}': 'Time chart {{index}}',
    '频域图 {{index}}': 'Frequency chart {{index}}',
    '柱状图 {{index}}': 'Bar chart {{index}}',
    '时间': 'Time',
    '频率': 'Frequency',
    '幅值': 'Amplitude',
    '{{base}}（{{channel}}）': '{{base}} ({{channel}})',
    '调整通道:{{channel}}': 'Channel: {{channel}}',
    '统一量程': 'Shared scale',
    '差异量程': 'Own scale',
    '缩放横轴': 'Zoom X',
    '缩放纵轴': 'Zoom Y',
    '图表设置': 'Chart settings',
    '关闭图表': 'Close chart',
    '上移': 'Move up',
    '下移': 'Move down',
    '应用常用范围': 'Apply common range',
    '拖动排序': 'Drag to reorder',
    'FFT 窗口': 'FFT window',
    '帧间隔 ms': 'Frame interval ms',

    /* Send */
    '发送内容': 'Send content',
    '输入发送内容': 'Type the content to send',
    '输入发送内容；HEX 模式示例：AA 55 01 02': 'Content to send; in HEX mode, for example AA 55 01 02',
    '输入原始十六进制内容': 'Enter raw hexadecimal content',
    'HEX 内容，例如 AA 55 01': 'HEX content, e.g. AA 55 01',
    'HEX 匹配内容，例如 4F 4B': 'HEX to match, e.g. 4F 4B',
    '立即发送': 'Send now',
    '预设': 'Presets',
    '预设发送': 'Preset send',
    '展开预设发送': 'Expand preset send',
    '新增预设项': 'Add preset',
    '发送': 'Send',
    '期望接收': 'Expected reply',
    '期望接收，留空不匹配': 'Expected reply, empty to skip',
    '描述': 'Description',
    '快捷键': 'Shortcut',
    '匹配内容': 'Match content',
    '定时': 'Timed',
    '定时发送': 'Timed send',
    '启用定时发送': 'Enable timed send',
    '新增轮询项': 'Add poll item',
    '间隔时间': 'Interval',
    '循环列表按周期自动发送': 'Cycles through the list on a timer',
    '触发': 'Trigger',
    '触发发送': 'Trigger send',
    '启用触发发送': 'Enable trigger send',
    '新增触发规则': 'Add trigger rule',
    '触发内容': 'Trigger content',
    '命中规则后自动应答': 'Reply automatically when a rule matches',
    '命中后发送内容': 'Content sent on match',
    '命中后发送 HEX 内容': 'HEX content sent on match',
    '发送内容并等待期望接收，开关控制全局快捷键': 'Send content and wait for the expected reply, the switch controls the global shortcut',

    /* Monitor event tags */
    '√ 预设：{{label}}': '√ preset: {{label}}',
    '× 预设：{{label}}': '× preset: {{label}}',
    '预设：{{label}}': 'preset: {{label}}',
    '触发：{{label}}': 'trigger: {{label}}',

    /* Settings, config, clipboard */
    '清空配置': 'Clear',
    '清空缓存': 'Clear cache',
    '此操作会丢失当前设置': 'This will discard your current settings',
    '取消': 'Cancel',
    '确认': 'Confirm',
    '已复制': 'Copied',
    '复制失败': 'Copy failed',
    '当前配置已写入剪贴板。': 'The current settings are on the clipboard.',
    '已粘贴': 'Pasted',
    '粘贴失败': 'Paste failed',
    '剪贴板中未检测到有效的配置。': 'No usable settings found on the clipboard.',
    '当前无法访问剪贴板。': 'The clipboard is not accessible right now.',
    '已从剪贴板载入当前配置。': 'Loaded the current settings from the clipboard.',
    '已还原': 'Restored',
    '还原失败': 'Restore failed',
    '已恢复默认配置，仅保留示例项。': 'Defaults restored, only the example entries remain.',
    '无法恢复默认配置。': 'Cannot restore the default settings.',
    '仅应用解析配置': 'Apply parse settings only',

    /* Import and export */
    '导入完成': 'Import complete',
    '导入失败': 'Import failed',
    '导出完成': 'Export complete',
    '无法导出': 'Cannot export',
    '{{name}} 已添加到时间线列表。': '{{name}} was added to the timeline list.',
    '{{name}} 已导出为 {{format}}。': '{{name}} was exported as {{format}}.',
    '{{name}} 的解析结果已导出为 {{format}}。': '{{name}} parse results were exported as {{format}}.',
    '录制已保存': 'Recording saved',
    '{{name}} 已归档，共 {{count}} 段。': '{{name}} archived with {{count}} chunks.',
    '录制已保存：{{name}}（{{count}} 段）。': 'Recording saved: {{name}} ({{count}} chunks).',
    '时间线仅支持 BIN / TXT / CSV。': 'Timelines support BIN / TXT / CSV only.',
    '解析结果仅支持 TXT / CSV。': 'Parse results support TXT / CSV only.',
    '当前规则没有生成可导出的数值结果。': 'The current rule produced no numeric results to export.',
    '请先选择一条已归档的时间线。': 'Select an archived timeline first.',
    '仅支持 BIN / TXT / CSV version 1 时间线文件。': 'Only version 1 BIN / TXT / CSV timeline files are supported.',
    '仅支持 version 1 原始时间线格式。': 'Only version 1 raw timeline format is supported.',
    '仅支持 CSV1 时间线格式。': 'Only the CSV1 timeline format is supported.',
    '仅支持 TXT1 时间线格式。': 'Only the TXT1 timeline format is supported.',
    'BIN 文件头不匹配。': 'The BIN header does not match.',
    'CSV 时间线缺少数据区。': 'The CSV timeline has no data section.',
    'TXT 时间线缺少数据区。': 'The TXT timeline has no data section.',
    '时间线缺少配置快照。': 'The timeline has no settings snapshot.',
    '无法解析时间线数据。': 'Cannot parse the timeline data.',
    '非法 HEX 字节: {{byte}}': 'Invalid HEX byte: {{byte}}',

    /* Statistics */
    '发送字节数': 'TX bytes',
    '接收字节数': 'RX bytes',
    '原始字节数': 'Raw bytes',
    '发送字节和': 'TX byte sum',
    '接收字节和': 'RX byte sum',
    '原始字节和': 'Raw byte sum',
    '发送首字节': 'First TX byte',
    '接收首字节': 'First RX byte',

    /* How-to tips */
    '如何编写解析规则： 三种标记（必须 / 开头 + 数字序号）： /nameN → 匹配文本，用作键名 /intN → 匹配整数 /floatN → 匹配小数 标记之间可放任意分隔符 分隔符按原样匹配输入数据 例 1：/name0=/int0 /name1=/float1 可解析：温度=42 湿度=3.14 结果→ 温度:42, 湿度:3.14 例 2：/name0:/int0,/name1=/float1 可解析：温度:42,湿度=3.14 例 3（动态键名）：/name0=/int0 同一规则可解析不同输入： 传感器A=25 → 传感器A:25 传感器B=30 → 传感器B:30 name 会自动将捕获的文本 作为该条数据的键名': 'How to write a parse rule: three tokens, each starting with / plus an index: /nameN → matches text and uses it as the key /intN → matches an integer /floatN → matches a decimal Separators between tokens are free and are matched literally against the input. Example 1: /name0=/int0 /name1=/float1 parses Temperature=42 Humidity=3.14 into Temperature:42, Humidity:3.14 Example 2: /name0:/int0,/name1=/float1 parses Temperature=42,Humidity=3.14 Example 3 (dynamic keys): /name0=/int0 one rule, different inputs: SensorA=25 → SensorA:25 SensorB=30 → SensorB:30 name uses whatever text it captured as the key of that reading',
    '行类型（按表格下拉顺序）： • 帧头 — 帧起始标识，16进制 留空则跳过 • 帧尾 — 帧结束标识，16进制 留空则不检查帧尾 • 数据 — 数值数据，需选择 数据类型 + 填写标签名 • 校验和 — 自动计算 SUM8 仅覆盖 data 行的字节 • 间隔符 — 留空占位 1 字节 填入则匹配指定16进制 数值大小端说明： LE = Little Endian（低位在前） BE = Big Endian（高位在前） 可用数据类型： UInt8 / Int8 UInt16 LE/BE / Int16 LE/BE UInt32 LE/BE / Int32 LE/BE Float32 LE/BE / Bool(8bit)': 'Row types (in the order of the table drop-downs): • Header — frame start, hexadecimal, leave empty to skip • Footer — frame end, hexadecimal, leave empty to skip the check • Data — numeric value, needs a data type plus a label • Checksum — SUM8 computed automatically over the Data rows only • Gap — empty means one placeholder byte, filled means match that byte Endianness: LE = Little Endian (low byte first) BE = Big Endian (high byte first) Data types: UInt8 / Int8 UInt16 LE/BE / Int16 LE/BE UInt32 LE/BE / Int32 LE/BE Float32 LE/BE / Bool(8bit)',

    /* Changelog: feature blurbs per release */
    'v0.3.0 版本 · 26/10/1': 'v0.3.0 · 26/10/1',
    '界面现在明确标注分叉身份：关于弹窗写清上游项目、分叉提交（e3f9200814，上游 v1.6，2026/9/6）以及各处构建的托管位置；☰ 菜单与弹窗里的链接改为指向本仓库，不再指向原作者的主机。': 'The interface now states that this is a fork: the About dialog names the upstream project, the divergence commit (e3f9200814, upstream v1.6, 2026/9/6) and where each build lives, and the ☰ menu and dialog links point at this repository instead of the original author\'s host.',
    '关于弹窗新增许可证一行，仓库补上 LICENSE：SerialWeb 采用上游声明的 AGPL-3.0 许可证。': 'Added a License row to the About dialog plus a LICENSE file: SerialWeb is AGPL-3.0, the license the upstream project declares.',
    '线上构建不再发送上游的页面访问统计——该请求只在原作者的主机上发出，因此 GitHub Pages 或 localhost 部署不会产生统计请求。': 'The hosted build no longer sends the upstream page-view request — it fires only on the original author\'s host, so a GitHub Pages or localhost deployment makes no analytics call.',
    '新增 GitHub Actions 工作流：构建 dist/SerialWeb.html 并作为 index.html 发布到 GitHub Pages。': 'Added a GitHub Actions workflow that builds dist/SerialWeb.html and publishes it to GitHub Pages as index.html.',
    '文档：新增中英双语的分叉来源，并用 tools/docs-check.py 校验文档链接、标题锚点与中英镜像。': 'Documentation: new fork provenance page in both languages, and tools/docs-check.py verifies doc links, heading anchors and the English/Chinese mirror.',
    'v0.2.0 版本 · 26/10/1': 'v0.2.0 · 26/10/1',
    '新增语言切换：系统菜单 ☰ 中提供 中文 / English / 跟随系统。切换即时生效、无需刷新并会被保存；只有界面会被翻译，已捕获的日志行与终端历史保持写入时的语言。': 'Added language switching: 中文 / English / Follow system in the system menu (☰). The choice is applied instantly, needs no reload and persists; only the interface is translated, captured log lines and terminal history keep the language they were written in.',
    '终端字体选择器现在诚实了：未检测到安装的字体族会被置灰并给出提示，而不是像以前那样静默地渲染成与默认等宽字体完全相同的样子。': 'The terminal font picker is now honest: families that are not installed on the machine are greyed out with a tooltip, instead of silently rendering like the default monospace font.',
    '字体与主题改动在终端隐藏时（手动视图或监视器收起）也能可靠生效——改动会被挂起，待终端重新可见时应用。': 'Font and theme changes now apply reliably, including while the terminal is hidden (manual view or the collapsed monitor) — the pending change is applied when the terminal becomes visible again.',
    '新增终端字号输入框（8–48 px，默认 12），并支持终端内 Ctrl + 鼠标滚轮缩放。两者都会被持久化。': 'Added a terminal font size field (8–48 px, default 12) and Ctrl + mouse wheel zoom over the terminal. Both persist.',
    '清空配置现在同时重置语言与终端字体/字号，并立即重新应用。': 'Clear config now also resets the language and the terminal font/size, and re-applies them live.',
    '支持串口监视、设备连接管理、VID/PID 显示、串口参数配置及硬件流控与信号控制。': 'Serial monitoring, device connection manager, VID/PID display, port settings, hardware flow control and signal control.',
    '支持手动、定时、触发和预设发送等串口调试工作流。': 'Manual, timed, trigger-based and preset sending workflows for serial debugging.',
    '支持图形解析，含文本解析、十六进制结构解析、自动识别规则及实时结果展示。': 'Graph parsing with text rules, hex structure decoding, auto-detected patterns and live results.',
    '支持时域图与频域图绘制，可绑定解析通道并调整视图范围与量程策略。': 'Time and frequency charts with channel binding, view range and scaling strategy.',
    '支持时间线系统，含实时冻结、录制归档、回放、导入导出与解析配置复用。': 'Timeline system with live freeze, recording, playback, import/export and reusable parse settings.',
    '支持高级发送展开区高度拖动调整及各模块拖拽排序。': 'Resizable advanced send area and drag-to-reorder for every module.',
    '支持设置、输入状态在退出后自动保存，下次加载时恢复使用。': 'Settings and input state are saved on exit and restored on the next load.',
    '支持深浅主题自动切换及宽屏/窄屏两种布局策略。': 'Automatic light/dark theme switching with wide and narrow layout strategies.',
    '支持离线版本的下载和离线版本使用，并支持离线状态识别。': 'Download and run the offline build, with offline state detection.',
    '支持预设发送添加备注描述，监视器中显示发送与匹配状态标识。': 'Preset entries take a description, and the monitor shows send and match status tags.',
    '支持定时、触发和预设发送在十六进制模式下保留原始字节，统一发送匹配与显示逻辑。': 'Timed, trigger and preset sends keep their raw bytes in HEX mode, with one shared send/match/display logic.',
    '新增关于弹窗、版本日志、工具手册、GitHub 和问题反馈入口。': 'Added the about dialog, changelog, manual, GitHub and feedback entries.',
    '新增全局配置导入导出与还原，统一保存设备、发送、解析及图框配置。': 'Added global settings import/export and restore, covering device, send, parse and chart configuration.',
    '新增柱状图，支持通道选择、纵轴缩放与自动量程。': 'Added the bar chart with channel selection, Y zoom and auto range.',
    '新增解析配置帮助提示，支持悬浮查看规则说明。': 'Added parse help, hover to read the rule syntax.',
    'name 标签匹配逻辑改为后缀数字匹配（name0↔int0），规则格式更灵活。': 'name tokens now match by index suffix (name0 ↔ int0), making rule syntax more flexible.',
    '预设发送支持单字符快捷键，按下即发；自动全选，替换即生效。': 'Preset send supports single-key shortcuts that fire on press; text is auto-selected so replacing takes effect at once.',
    '加入自动重连机制，设备插拔或连接丢失后可尝试恢复。': 'Added auto reconnect to recover after a replug or a lost connection.',
    '加入失焦自动断连机制，窗口失焦时释放串口，恢复焦点后继续使用。': 'Added release-on-blur: the port is freed when the window loses focus and reused when it returns.',
    '优化页面配色与扁平化设计，浅色/深色模式分离。': 'Refined the palette and flat design, with separate light and dark schemes.',
    '优化紧凑显示模式、布局间距与各面板一致性。': 'Improved compact display, spacing and panel consistency.',
    '优化视觉效果，包括弹窗、下拉状态和窄屏悬浮窗的模糊背景。': 'Polished visuals: dialogs, dropdown states and the blurred backdrop of narrow-screen popovers.',
    '优化模板解析、发送数据过滤与复选框样式统一。': 'Improved pattern parsing, send data filtering and consistent checkbox styling.',
    '优化实时解析结果展示，支持横向滚动、展开和折叠。': 'Improved live parse results with horizontal scroll, expand and collapse.',
    '优化通道交互、图框渲染、频域图通道筛选与 name 动态字段跟踪。': 'Better channel interaction, chart rendering, frequency channel filtering and dynamic name tracking.',
    '优化图框的部分显示效果和操作逻辑。': 'Improved parts of the chart display and its controls.',
    '优化设备连接管理中组件的显示效果。': 'Improved component display in the device connection manager.',
    '优化预设发送交互逻辑，通过开关控制全局快捷键的预设发送。': 'Refined preset send: a switch controls whether the global shortcut fires it.',
    '优化十六进制结构解析，支持间隔符占位和帧尾留空的宽匹配逻辑。': 'Improved hex structure parsing with gap placeholders and a lenient empty-footer match.',
    '优化时间线回放、配置导入导出的图框状态同步与持久化。': 'Better timeline playback and chart state sync/persistence on settings import/export.',
    '重构 TX/RX 收发与换行符显示逻辑，优化监视器渲染与事件处理。': 'Rewrote TX/RX and line-ending display, with faster monitor rendering and event handling.',
    '"自动硬件流控"更名为"RTS/CTS 流控"，名称更准确。': 'Renamed "Auto hardware flow control" to "RTS/CTS flow control", which is what it actually does.',
    '修正连接状态下修改串口参数未立即生效的问题。': 'Fixed port settings changes not taking effect while connected.',
    '修复串口接收数据特殊情况下监视器多出空行的问题。': 'Fixed spurious blank lines in the monitor for certain received data.',
    '修复 GitHub 历史版本仓库，优化离线版本使用体验。': 'Fixed the GitHub history repo and improved the offline experience.',
    '分叉基线：上游 v1.6（提交 e3f9200814）；本仓库把单文件拆成源码分片，并新增了上游没有的 xterm 终端视图。': 'Fork baseline: upstream v1.6 (commit e3f9200814). This repository splits the single file into source chunks and adds the xterm terminal view, which upstream v1.6 does not have.',
    'v1.0 版本 · 26/5/24': 'v1.0 · 26/5/24',
    'v1.1 版本 · 26/5/30': 'v1.1 · 26/5/30',
    'v1.2 版本 · 26/6/11': 'v1.2 · 26/6/11',
    'v1.3 版本 · 26/6/30': 'v1.3 · 26/6/30',
    'v1.4 版本 · 26/7/4': 'v1.4 · 26/7/4',
    'v1.5 版本 · 26/7/9': 'v1.5 · 26/7/9',
    'v0.1.0 版本 · 26/9/30': 'v0.1.0 · 26/9/30 (was v1.6)'
  };

  window.SERIALWEB_I18N = { en: en };
})();
